apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp
 labels:
  tier: frontend
  app: nginx
spec:
 template:
  metadata:
    name: myapp
    labels:
      name: myapp
  spec:
    containers:
      - name: nginx
        image: nginx
 selector:
  matchLabels:
    name: myapp
 replicas: 3
